"""Add Skill, SubSkill, and project_subskill relationship

Revision ID: 691144dedacc
Revises: 6d82dae3ffad
Create Date: 2025-09-02 07:46:33.057367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691144dedacc'
down_revision = '6d82dae3ffad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sub_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_subskill',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subskill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['subskill_id'], ['sub_skill.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'subskill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_subskill')
    op.drop_table('sub_skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
